DROP TABLE IF EXISTS characters, locations, episodes, qoutes;

CREATE TABLE characters (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    species TEXT NOT NULL
);

CREATE TABLE locations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    dimension TEXT NOT NULL
);

CREATE TABLE episodes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    episode TEXT NOT NULL
);

CREATE TABLE qoutes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    character TEXT NOT NULL
);

